name: Docker CI Unstable
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build Docker image for ARM
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: ./Dockerfile-arm
        push: true
        tags: cyfershepard/jellystat:unstable-arm

    - name: Build Docker image for AMD64 (optional)
      uses: docker/build-push-action@v2
      with:
        context: .
        dockerfile: ./Dockerfile-arm
        push: true
        tags: cyfershepard/jellystat:arm
